### ISSUE TITLE
What is Webpack and is it needed or not needed for connection over LAN?

### ISSUE THREAD

**Issue by arunkumaraqm** [arunkumaraqm/Video-Conferencing-Webrtc#4]
Akhil had Webpack in his packages.json and said that he had installed it while trying to get it working over LAN. But is it needed to serve the project?

**Comment by AkhilT-Sam** [comment]
Webpack isn't needed to serve the project over LAN. I did `npm uninstall webpack` and `npm uninstall webpack dev-server` on a clone project and tried to serve it over LAN. It worked fine.
